"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-08-08 14:47:04.197837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=16), server_default=sa.text("'member'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='ck_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('asset',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('taken_local', sa.DateTime(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tz_offset', sa.Integer(), nullable=True),
    sa.Column('taken_md', sa.SmallInteger(), sa.Computed('EXTRACT(MONTH FROM taken_local)::int * 100 + EXTRACT(DAY FROM taken_local)::int', persisted=True), nullable=False),
    sa.Column('date_source', sa.String(length=16), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('camera', sa.Text(), nullable=True),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('codec', sa.String(length=16), nullable=True),
    sa.Column('is_hdr', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('needs_display_copy', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('derive_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('video_status', sa.String(length=16), nullable=True),
    sa.Column('content_id', sa.Text(), nullable=True),
    sa.Column('live_motion_id', sa.Uuid(), nullable=True),
    sa.Column('is_live_motion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_screenshot', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rotation', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("date_source IN ('exif', 'xmp', 'filename', 'sibling', 'mtime', 'manual', 'unknown')", name='ck_asset_date_source'),
    sa.CheckConstraint("derive_status IN ('pending', 'ready', 'failed')", name='ck_asset_derive_status'),
    sa.CheckConstraint("kind IN ('image', 'video')", name='ck_asset_kind'),
    sa.CheckConstraint("video_status IS NULL OR video_status IN ('direct', 'needs_transcode', 'ready', 'failed')", name='ck_asset_video_status'),
    sa.CheckConstraint('rotation IN (0, 90, 180, 270)', name='ck_asset_rotation'),
    sa.ForeignKeyConstraint(['live_motion_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_asset_sha256')
    )
    op.create_index('ix_asset_content_id', 'asset', ['content_id'], unique=False, postgresql_where=sa.text('content_id IS NOT NULL'))
    op.create_index('ix_asset_exif', 'asset', ['exif'], unique=False, postgresql_using='gin')
    op.create_index('ix_asset_on_this_day', 'asset', ['taken_md', sa.literal_column('taken_local DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_asset_timeline', 'asset', [sa.literal_column('taken_at DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('album',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cover_asset_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_tag',
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id')
    )
    op.create_table('ingest_log',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('source_filename', sa.Text(), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event IN ('ingested', 'duplicate', 'restored', 'failed')", name='ck_ingest_log_event'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingest_log_created', 'ingest_log', [sa.literal_column('created_at DESC')], unique=False)
    op.create_table('album_asset',
    sa.Column('album_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'asset_id')
    )
    op.create_table('share_link',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('album_id', sa.Uuid(), nullable=True),
    sa.Column('asset_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('allow_download', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(album_id, asset_id) = 1', name='ck_share_link_target'),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_link')
    op.drop_table('album_asset')
    op.drop_index('ix_ingest_log_created', table_name='ingest_log')
    op.drop_table('ingest_log')
    op.drop_table('asset_tag')
    op.drop_table('album')
    op.drop_index('ix_asset_timeline', table_name='asset', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_asset_on_this_day', table_name='asset', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_asset_exif', table_name='asset', postgresql_using='gin')
    op.drop_index('ix_asset_content_id', table_name='asset', postgresql_where=sa.text('content_id IS NOT NULL'))
    op.drop_table('asset')
    op.drop_table('tag')
    op.drop_table('app_user')
    # ### end Alembic commands ###
